server {
    listen 80;
    server_name bc-portal-dev.tanuh.ai;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bc-portal-dev.tanuh.ai;

    ssl_certificate /etc/letsencrypt/live/bc-portal-dev.tanuh.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bc-portal-dev.tanuh.ai/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 150M;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
